api7/website

data/news.json
=> docs: add news `36氪首发｜ 云原生 API 处理平台「支流科技」完成百万美元 Pre-A 轮融资，已有近200名代码贡献者`

_posts/blog/en-US/install-apache-apisix-from-helm-charts.md, _posts/blog/zh-CN/install-apache-apisix-from-helm-charts.md, data/blog.json
=> feat: add Install Apache APISIX from Helm Charts blog

_posts/blog/en-US/get-front-end-test-coverage-with-cypress.md, _posts/blog/zh-CN/get-front-end-test-coverage-with-cypress.md, data/blog.json
Added a blog `Get Front-End Test Coverage with Cypress`
=> docs: added blog `Get Front-End Test Coverage with Cypress`

components/Nav/Nav.tsx, components/Nav/style.ts
resolve #13 
Show menu content on mouse hover
=> feat: menu shows when hover

public/static/locales/en-US/common.json, public/static/locales/zh-CN/common.json
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
So users would know how to change
=> fix: language should show up as the opposite one

components/Nav/Nav.tsx, pages/contributor-graph/index.js, public/static/locales/en-US/common.json, public/static/locales/zh-CN/common.json, views/Contributor/Contributor.tsx, views/Contributor/index.ts, views/Contributor/style.ts
1. update the nav
2. added page for `contributor-graph`
=> feat: update Nav and added `page for contributor-graph`

pages/_document.tsx
=> feat: added keywords for head

components/HomeBanner/index.tsx, components/Navbar/NavContent.tsx, views/Home/components/HomeFeature2/index.tsx, views/Home/components/HomeFeature3/index.tsx, views/Home/components/HomeHero/index.tsx
=> feat: update logos & language switcher

_posts/blog/en-US/traffic-split-in-apache-apisix-ingress-controller.md, _posts/blog/zh-CN/traffic-split-in-apache-apisix-ingress-controller.md, data/blog.json, views/Post/style.ts
resolve #38 
1. Add a new blog post.
TODO:
=> doc: added blog "Traffic Split in Apache APISIX Ingress Controller"

views/Home/components/HomeHero/index.tsx
=> ui: update logo wall on the homepage

components/Footer/_data.tsx, components/Footer/index.tsx, components/HomeBanner/index.tsx, components/Navbar/_data.tsx, public/static/locales/en-US/home.json, views/Home/components/HomeFeature2/index.tsx, views/Home/components/HomeFeature3/index.tsx, views/Home/components/HomeHero/index.tsx
=> improve UI on the homepage

views/Post/Post.tsx
resolve #33 
update English article page date, use DD-MM-YYYY for English page.
=> feat: use DDMMYYYY for English articles

views/Home/components/HomeFeature4/_data.ts, views/Post/style.ts
=> docs: added traffic split post on the Home page

data/news.json
=> docs: added news "支流科技：社区是杠杆，让付费用户主动找来"

README.md
=> docs: more clearance to installation of repo in README.md

views/Team/_data.tsx
added new memeber Yeliang Wang
=> docs: added new member

_posts/blog/en-US/a-first-look-at-kubernetes-service-api.md, _posts/blog/en-US/analysis-of-inaccurate-distribution-of-wrk-latency.md, _posts/blog/en-US/another-way-to-implement-envoy-filter.md, _posts/blog/en-US/apache-apisix-helps-enterprises-transform-digitally.md, _posts/blog/en-US/get-front-end-test-coverage-with-cypress.md, _posts/blog/en-US/how-Amazon-EKS-and-APISIX-ingress-controller-work-together-to-manage-complex-traffic.md, _posts/blog/en-US/how-to-build-gateway-based-on-apache-apisix.md, _posts/blog/zh-CN/a-first-look-at-kubernetes-service-api.md, _posts/blog/zh-CN/analysis-of-inaccurate-distribution-of-wrk-latency.md, _posts/blog/zh-CN/another-way-to-implement-envoy-filter.md, _posts/blog/zh-CN/get-front-end-test-coverage-with-cypress.md, _posts/blog/zh-CN/how-Amazon-EKS-and-APISIX-ingress-controller-work-together-to-manage-complex-traffic.md, _posts/page/en-US/apisix-vs-api7.md
=> fix: broken links

components/Navbar/NavMenu.tsx
=> fix: removed motion.custom() deprecation warning

views/Post/style.ts
1. Changing the width of the parent container
2. Change table items to a fixed width
=> style: Change article page style.

components/Footer/_data.tsx, views/About/About.tsx, views/Home/components/HomeCTA/index.tsx
=> chore: use support@api7.ai

components/Navbar/NavContent.tsx
resolve #72 
This PR updates the text of the Navbar Experience Demo.
=> chore: update nav bar

data/news.json, views/Home/components/HomeFeature4/_data.ts
This PR aims to add the article: https://mp.weixin.qq.com/s/DDCKSVshAbNQmCgY8Z4M4Q
=> docs: added CAICT docs

components/Footer/_data.tsx, components/Navbar/_data.tsx
This PR aims to add links for service mesh
=> docs: added Service Mesh

views/Contributor/Contributor.tsx, views/Contributor/style.ts
This PR is aim to do:
-  remove useless code
-  update contributor over time iframe style
=> feat: update contributor over time iframe style

views/Contributor/Contributor.tsx, views/Contributor/style.ts
This PR aims to update the style for mobile adaptation.
The  mobile page will show as below:
=> feat: update style for mobile adaptation

data/news.json, views/Home/components/HomeFeature4/_data.ts
=> docs: update post title

components/Footer/_data.tsx, views/About/About.tsx, views/Home/components/HomeCTA/index.tsx
=> Revert "chore: use support@api7.ai"

components/Footer/_data.tsx, views/About/About.tsx, views/Home/components/HomeCTA/index.tsx
=> Revert "Revert "chore: use support@api7.ai""

views/Contributor/Contributor.tsx
adaptation for sharing contributor monthly activity
=> feat: adaptation for sharing contributor monthly activity

next.config.js
Docs: https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix
=> feat: support custom asset

next.config.js
=> Revert "feat: support custom asset"

public/static/locales/en-US/about.json, public/static/locales/zh-CN/about.json, views/About/About.tsx, views/Home/components/HomeCertificates/index.tsx
=> remove extra mails & fix Certificates styles

data/about.json, data/news.json
This PR aims to add A+ funding news on the following pages:
=> docs: added A+ funding news

_posts/page/en-US/apisix-vs-api7.md
=> fix: error display in apisix-vs-api7 en

_posts/page/zh-CN/apisix-vs-api7.md
Signed-off-by: yiyiyimu <wosoyoung@gmail.com>
=> chore: change link to master version

data/usercase.json, views/Home/components/HomeFeature4/_data.ts
Changes：
feat: update usercase and home page blog card
=> feat: update usercase and home page blog card

_posts/usercase/zh-CN/iQIYI.md, data/usercase.json
=> docs: add iQIYI article.md

_posts/blog/zh-CN/python-helps-you-quickly-with-Apache-APISIX-plugin-development.md, data/blog.json
added python helps you quickly with Apache APISIX plugin development blog
=> docs: added python helps you quickly with Apache APISIX plugin article

_posts/blog/zh-CN/Extension-guide.md, data/blog.json
=> docs: add extention guide blog

views/Features/Features.tsx, views/Features/style.ts
Dynamically set the height of the navigation bar
=> feat: dynamic update of the secondary navigation position of the feature list page

views/Team/_data.tsx
=> docs: add team member twitter
